language: php
before_script: composer install --dev --prefer-source --no-interaction
script: phpunit tests/ --coverage-clover build/logs/clover.xml
after_script:
  - travis_retry php vendor/bin/coveralls
